spring.application.name=PokedexApi
spring.application.version=1.6.0
spring.jmx.enabled=true
spring.main.allow-bean-definition-overriding=true

skaro.pokeapi.baseUri=https://pokeapi.co/api/v2/
skaro.pokeapi.maxBytesToBuffer=5065000
server.tomcat.connection-timeout=200000
server.servlet.context-path=/
spring.profiles.active=production
#server.port=4204
# http://<HOST><CONTEXT-PATH>/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.showExtensions=true
springdoc.swagger-ui.displayRequestDuration=true

