
skaro.pokeapi.baseUri=https://pokeapi.co/api/v2/
skaro.pokeapi.maxBytesToBuffer=5065000

server.port=4204
server.servlet.context-path=/pokedexapi

# http://<HOST><CONTEXT-PATH>/swagger-ui/index.html
springdoc.swagger-ui.url=/pokedexapi/v3/api-docs
springdoc.swagger-ui.url-docs=/pokedexapi/v3/api-docs